import { useState } from 'react'
import { insightsApi } from '../utils/api'
import { Lightbulb, Brain, Sparkles, RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'

function InsightBlock({ title, icon: Icon, content, loading, onGenerate, color = 'primary' }) {
  const colorMap = {
    primary: { bg: 'bg-primary-600/10', border: 'border-primary-600/20', icon: 'text-primary-400', btn: 'btn-primary' },
    purple: { bg: 'bg-purple-600/10', border: 'border-purple-600/20', icon: 'text-purple-400', btn: 'bg-purple-600 hover:bg-purple-500 text-white font-medium px-4 py-2 rounded-lg transition-colors' },
  }
  const c = colorMap[color]

  return (
    <div className={`card border ${c.border} ${c.bg}`}>
      <div className="flex items-center justify-between mb-4">
        <h3 className={`font-semibold text-white flex items-center gap-2`}>
          <Icon size={15} className={c.icon} />
          {title}
        </h3>
        <button
          onClick={onGenerate}
          disabled={loading}
          className={`${c.btn} flex items-center gap-2 text-sm disabled:opacity-50`}
        >
          {loading ? (
            <>
              <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles size={13} />
              {content ? 'Regenerate' : 'Generate'}
            </>
          )}
        </button>
      </div>

      {content ? (
        <div className="prose prose-invert max-w-none">
          <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap bg-dark-700/50 rounded-xl p-4 border border-dark-600">
            {content}
          </div>
        </div>
      ) : (
        <div className="text-center py-8">
          <Icon size={32} className={`${c.icon} mx-auto mb-2 opacity-40`} />
          <p className="text-gray-500 text-sm">Click Generate to get AI-powered insights</p>
          <p className="text-gray-600 text-xs mt-1">Powered by Llama3 via Ollama</p>
        </div>
      )}
    </div>
  )
}

export default function InsightsTab({ datasetId }) {
  const [autoInsight, setAutoInsight] = useState('')
  const [mlInsight, setMlInsight] = useState('')
  const [loadingAuto, setLoadingAuto] = useState(false)
  const [loadingMl, setLoadingMl] = useState(false)

  const genAuto = async () => {
    setLoadingAuto(true)
    try {
      const res = await insightsApi.auto(datasetId)
      setAutoInsight(res.data.insights)
    } catch (e) {
      toast.error(e.response?.data?.detail || 'Failed to generate insights')
    } finally {
      setLoadingAuto(false)
    }
  }

  const genMl = async () => {
    setLoadingMl(true)
    try {
      const res = await insightsApi.mlExplain(datasetId)
      setMlInsight(res.data.explanation)
    } catch (e) {
      toast.error(e.response?.data?.detail || 'Train a model first to get ML insights')
    } finally {
      setLoadingMl(false)
    }
  }

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Info Banner */}
      <div className="card border-dark-500 bg-dark-700/40">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-primary-600/20 rounded-lg shrink-0 mt-0.5">
            <Brain size={16} className="text-primary-400" />
          </div>
          <div>
            <div className="font-medium text-gray-200 text-sm mb-1">Powered by Llama3 (Ollama)</div>
            <div className="text-gray-400 text-xs leading-relaxed">
              These insights are generated by a local Llama3 model running via Ollama.
              Make sure Ollama is running (<code className="bg-dark-600 px-1 rounded text-primary-300">ollama serve</code>) and
              the model is pulled (<code className="bg-dark-600 px-1 rounded text-primary-300">ollama pull llama3</code>).
            </div>
          </div>
        </div>
      </div>

      <InsightBlock
        title="Dataset Overview Insights"
        icon={Lightbulb}
        content={autoInsight}
        loading={loadingAuto}
        onGenerate={genAuto}
        color="primary"
      />

      <InsightBlock
        title="ML Model Explanation"
        icon={Brain}
        content={mlInsight}
        loading={loadingMl}
        onGenerate={genMl}
        color="purple"
      />
    </div>
  )
}
